# Generated by Django 4.0.5 on 2022-07-11 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(upload_to='homeworks/questions/'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_homework_file',
            field=models.FileField(blank=True, upload_to='homeworks/answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt'])]),
        ),
    ]
