# Generated by Django 4.0.5 on 2022-07-13 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_studentgroup_student'),
        ('courses', '0002_alter_homework_homework_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user.teacher'),
        ),
    ]
