# Generated by Django 4.0.5 on 2022-07-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('courses', '0002_alter_homework_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student_group',
            field=models.ManyToManyField(to='user.studentgroup'),
        ),
    ]
