# Generated by Django 4.0.5 on 2022-07-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_homeworksubmission_file_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='file_ratings',
        ),
    ]
