# Generated by Django 4.0.5 on 2022-07-13 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_studentgroup_student'),
        ('courses', '0003_alter_homework_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(upload_to='homeworks/questions/group/'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_rating',
            field=models.FloatField(blank=True, max_length=5),
        ),
        migrations.CreateModel(
            name='HomeworkStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('homework_title', models.CharField(max_length=255)),
                ('homework_text', models.TextField(blank=True)),
                ('homework_file', models.FileField(upload_to='homeworks/questions/student/')),
                ('homework_created_time', models.DateTimeField(auto_now_add=True)),
                ('homework_deadline_time', models.DateTimeField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('upload_homework_time', models.DateTimeField(auto_now_add=True)),
                ('answer_file', models.FileField(blank=True, upload_to='homeworks/answers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt'])])),
                ('answer_rating', models.FloatField(blank=True, max_length=5)),
                ('homework_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homeworkstudent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
