# Generated by Django 4.0.5 on 2022-07-16 10:50

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_homework_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_deadline_time',
            field=models.DateTimeField(blank=True, null=True, validators=[courses.models.deadline_time]),
        ),
    ]
