# Generated by Django 4.0.5 on 2022-07-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_file_ratings'),
        ('courses', '0004_remove_homeworksubmission_file_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='user.student'),
        ),
    ]
