# Generated by Django 4.0.5 on 2022-07-18 05:13

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_homework_homework_deadline_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_deadline_time',
            field=models.DateTimeField(validators=[courses.models.deadline_time]),
        ),
    ]
