# Generated by Django 4.0.5 on 2022-07-13 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_homeworksubmission_submission_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
