# Generated by Django 4.0.5 on 2022-07-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_homework_homework_deadline_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
