# Generated by Django 4.0.5 on 2022-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_file_ratings'),
        ('courses', '0005_remove_homework_student_homework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ManyToManyField(blank=True, to='user.student'),
        ),
    ]
