# Generated by Django 4.0.5 on 2022-07-13 06:44

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_homeworksubmission_submission_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_deadline_time',
            field=models.DateTimeField(null=True, validators=[courses.models.deadline_time]),
        ),
        migrations.AlterField(
            model_name='homeworkstudent',
            name='homework_deadline_time',
            field=models.DateTimeField(null=True, validators=[courses.models.deadline_time]),
        ),
    ]
