# Generated by Django 4.0.5 on 2022-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('courses', '0007_alter_homeworksubmission_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student_group',
            field=models.ManyToManyField(related_name='Group', to='user.studentgroup'),
        ),
    ]
