# Generated by Django 4.0.5 on 2022-07-13 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_homework_homework_deadline_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='answer_rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
