# Generated by Django 4.0.5 on 2022-07-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('courses', '0011_alter_homework_homework_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='user.studentgroup'),
        ),
    ]
