# Generated by Django 4.0.5 on 2022-07-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
