# Generated by Django 4.0.6 on 2022-07-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500, null=True)),
                ('zoom_start_url', models.URLField(blank=True, max_length=500, null=True)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.teacher')),
            ],
        ),
    ]
