# Generated by Django 4.0.5 on 2022-07-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_ratings',
            field=models.FileField(blank=True, upload_to='ratings/'),
        ),
    ]
