# Generated by Django 4.0.5 on 2022-07-04 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_adminstator_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstator',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Famale', 'Famale')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminstator',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
