# Generated by Django 4.0.5 on 2022-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='student',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='student',
            field=models.ManyToManyField(to='user.student'),
        ),
    ]
