# Generated by Django 4.0.5 on 2022-07-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_adminstator_gender_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_images'),
        ),
    ]
