# Generated by Django 4.0.5 on 2022-07-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='user.student'),
        ),
    ]
