# Generated by Django 4.0.5 on 2022-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_studentgroup_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ManyToManyField(blank=True, to='user.student'),
        ),
    ]
