# Generated by Django 4.0.5 on 2022-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_student_group_alter_studentgroup_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ManyToManyField(to='user.student'),
        ),
    ]
