# Generated by Django 4.0.5 on 2022-07-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_studentgroup_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.admin'),
        ),
    ]
