# Generated by Django 4.0.5 on 2022-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
