# Generated by Django 4.0.5 on 2022-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_student_education_start_date_teacher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_list', to='user.student'),
        ),
    ]
