# Generated by Django 4.0.6 on 2022-07-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_student_file_ratings'),
        ('chat', '0002_remove_message_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='user.studentgroup'),
        ),
    ]
