# Generated by Django 4.0.6 on 2022-08-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_activity'),
        ('chat', '0002_alter_message_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ManyToManyField(blank=True, to='user.studentgroup'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.teacher'),
        ),
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
