# Generated by Django 4.0.6 on 2022-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_group_room_owner_messageroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
