# Generated by Django 4.0.6 on 2022-07-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_teacher_alter_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='teacher',
        ),
    ]
