# Generated by Django 4.0.6 on 2022-07-26 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_student_file_ratings'),
        ('chat', '0004_remove_message_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.student'),
        ),
    ]
