# Generated by Django 4.0.6 on 2022-08-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageroom_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
