# Generated by Django 4.0.6 on 2022-08-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_activity'),
        ('chat', '0005_remove_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.teacher'),
        ),
    ]
