# Generated by Django 4.0.6 on 2022-08-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_messageroom_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageroom',
            options={'ordering': ('date_added',)},
        ),
    ]
